// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PRD_High_School.Models;

namespace PRDHighSchool.Migrations
{
    [DbContext(typeof(StudentContextModel))]
    [Migration("20191108101959_PrdDotNetDataBase")]
    partial class PrdDotNetDataBase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PRD_High_School.Models.StudentModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("Ammount");

                    b.Property<string>("Class")
                        .IsRequired();

                    b.Property<string>("CollectionDate")
                        .IsRequired();

                    b.Property<string>("DateofBirth")
                        .IsRequired();

                    b.Property<double>("FixedPrice");

                    b.Property<string>("PaymentType")
                        .IsRequired();

                    b.Property<string>("Section")
                        .IsRequired();

                    b.Property<string>("Status")
                        .IsRequired();

                    b.Property<string>("StudentId")
                        .IsRequired();

                    b.Property<string>("StudentName")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("StudentItems");
                });
#pragma warning restore 612, 618
        }
    }
}
